version: '3'

vars:
  submission_ids: 1 2 3 4 6 7 8 9 10 11 12
  package: CEUR/Package
  workshop: D2R2-23

tasks:
  default:
    - task -a

  compile:
    - |
      declare -A paper_id
      paper_id["Preface"]="preface"
      paper_id["01"]="paper01"
      paper_id["02"]="paper02"
      paper_id["03"]="paper03"
      paper_id["04"]="paper04"
      paper_id["06"]="paper06"
      paper_id["07"]="paper07"
      paper_id["08"]="paper08"
      paper_id["09"]="paper09"
      paper_id["10"]="paper10"
      paper_id["11"]="paper11"
      paper_id["12"]="paper12"

      mkdir -p {{.package}}/AGREEMENTS-{{.workshop}}/
      cp agreement-form/EDITOR-AGREEMENT-{{.workshop}}.pdf {{.package}}/AGREEMENTS-{{.workshop}} || touch {{.package}}/AGREEMENTS-{{.workshop}}/EDITOR-AGREEMENT-is-missing.pdf
      for submission_id in {{.submission_ids}}
      do
        cp agreement-form/$submission_id/agreement.pdf {{.package}}/AGREEMENTS-{{.workshop}}/AUTHOR-AGREEMENT-${paper_id["$submission_id"]}.pdf || touch {{.package}}/AGREEMENTS-{{.workshop}}/AUTHOR-AGREEMENT-${paper_id["$submission_id"]}-is-missing.pdf
      done
      cd {{.package}}
      zip -r AGREEMENTS-{{.workshop}}.zip AGREEMENTS-{{.workshop}}
      cd -

      mkdir -p {{.package}}/{{.workshop}}/
      cp index/_site/Vol-XXX/index.html {{.package}}/{{.workshop}}/index.html
      cp source-management/Preface/main.pdf {{.package}}/{{.workshop}}/preface.pdf || echo "skip"
      for submission_id in {{.submission_ids}}
      do
        cp source-management/$submission_id/main.pdf {{.package}}/{{.workshop}}/${paper_id["$submission_id"]}.pdf || echo "skip"
      done
      cd {{.package}}
      zip -r {{.workshop}}.zip {{.workshop}}
      cd -
