version: '3'

vars:
  submission_ids: 2 4 6 8 9 10 11

tasks:
  default:
    - task -l

  install:
    desc: Install dependencies and project
    cmds:
      - |
        poetry install

  build:
    desc: Batch build all agreement forms
    cmds:
      - |
        for submission_id in {{.submission_ids}}
        do
          submission_id=$submission_id task submission:build || true
        done
      - task: submission:build
        vars:
          submission_id: Preface
      - task: editor:build

  submission:build:
    desc: Build an author agreement form for a submission
    cmds:
      - |
        cd {{.submission_id}}
        poetry run fill_form --metadata metadata.yml --template ../ceur-author-agreement-ccby-ntp.pdf --output agreement_to_sign.pdf
    status:
      - test ! -f {{.submission_id}}/metadata.yml

  editor:build:
    desc: Build the editor agreement form for the proceedings
    cmds:
      - |
        poetry run fill_form --editor --metadata metadata-editor.yml --template ceur-editor-agreement-ccby.pdf --output editor_agreement_to_sign.pdf
    status:
      - test ! -f metadata-editor.yml
