version: '3'

vars:
  submission_ids: 1805 2109 2547 2553 3784 6009 6761 7697 8771 9422 9870 Preface
  package: CEUR/Package
  workshop: D2R2-23

tasks:
  default:
    - task -a

  compile:
    - |
      declare -A paper_id
      paper_id["Preface"]="preface"
      paper_id["1805"]="paper01"
      paper_id["6761"]="paper02"
      paper_id["7697"]="paper03"
      paper_id["2109"]="paper04"
      paper_id["8771"]="paper05"
      paper_id["3784"]="paper06"
      paper_id["2547"]="paper07"
      paper_id["6009"]="paper08"
      paper_id["9422"]="paper09"
      paper_id["2553"]="paper10"
      paper_id["9870"]="paper11"

      mkdir -p {{.package}}/AGREEMENTS-{{.workshop}}/
      cp Agreements/EDITOR-AGREEMENT-{{.workshop}}.pdf {{.package}}/AGREEMENTS-{{.workshop}} || touch {{.package}}/AGREEMENTS-{{.workshop}}/EDITOR-AGREEMENT-is-missing.pdf
      for submission_id in {{.submission_ids}}
      do
        cp Agreements/$submission_id/agreement.pdf {{.package}}/AGREEMENTS-{{.workshop}}/AUTHOR-AGREEMENT-${paper_id["$submission_id"]}.pdf || touch {{.package}}/AGREEMENTS-{{.workshop}}/AUTHOR-AGREEMENT-${paper_id["$submission_id"]}-is-missing.pdf
      done
      cd {{.package}}
      zip -r AGREEMENTS-{{.workshop}}.zip AGREEMENTS-{{.workshop}}
      cd -

      mkdir -p {{.package}}/{{.workshop}}/
      cp Index/_site/Vol-XXX/index.html {{.package}}/{{.workshop}}/index.html
      cp Sources/Preface/main.pdf {{.package}}/{{.workshop}}/preface.pdf
      for submission_id in {{.submission_ids}}
      do
        cp Sources/$submission_id/main.pdf {{.package}}/{{.workshop}}/${paper_id["$submission_id"]}.pdf
      done
      cd {{.package}}
      zip -r {{.workshop}}.zip {{.workshop}}
      cd -
