version: '3'

vars:
  origianl_submissions: ../D2R2_22_submissions_1805-9870_2022-11-30_1669817043
  submission_ids: 1805 2109 2547 2553 3784 6009 6761 7697 8771 9422 9870
    # sh: find . -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
  LATEX_IMAGE: latex-ceur:ubuntu

tasks:
  default:
    - task -l

  docker:build:
    desc: "Build the docker image. We need a TeX live 2021 or eariler distribution to correctly represent the ceur style."
    cmds:
      - docker build -t {{.LATEX_IMAGE}} .

  build:
    - |
      for submission_id in {{.submission_ids}}
      do
        submission_id=$submission_id task submission:build || true
      done
    - task: submission:build
      vars:
        submission_id: Preface

  clean:
    - |
      for submission_id in {{.submission_ids}}
      do
        submission_id=$submission_id task submission:clean
      done
    - task: submission:clean
      vars:
        submission_id: Preface

  cherry-diff:
    - |
      for submission_id in {{.submission_ids}}
      do
        git-cherry-file HEAD ${submission_id}/main.pdf ${submission_id}/cherry.pdf
        diffpdf ${submission_id}/main.pdf ${submission_id}/cherry.pdf
        rm ${submission_id}/cherry.pdf
      done

  open:
    - |
      for submission_id in {{.submission_ids}}
      do
        xdg-open $submission_id/main.pdf
      done
    - task: submission:open
      vars:
        submission_id: Preface

  diff:
    - |
      for submission_id in {{.submission_ids}}
      do
        submission_id=$submission_id task submission:diff
      done

  submission:diff:
    - diffpdf {{.submission_id}}/main.pdf {{.origianl_submissions}}/D2R222_paper_{{.submission_id}}.pdf

  submission:build:
    - |
      cd {{.submission_id}}
      exec docker run --rm -i --net=none -v "$PWD":/data "{{.LATEX_IMAGE}}" latexmk -lualatex -shell-escape main.tex

  submission:clean:
    - |
      cd {{.submission_id}}
      ../latexdockercmd.sh latexmk -c -lualatex main.tex
      rm main.abs || true
      rm main.xmpdata || true
      rm pdfa.xmpi || true
      rm creationdate.lua || true
      rm creationdate.timestamp || true
      rm *.xdv || true
      rm *.bbl || true
      rm -r _minted-main/ || true
