version: '3'

vars:
  origianl_submissions: ../D2R2_23_submissions # downloaded from easychair
  submission_ids: 2 4 6 8 9 10 11
    # sh: find . -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
  LATEX_IMAGE: ghcr.io/aksw/submission.d2r2.aksw.org:docker-image

tasks:
  default:
    - task -l

  docker:build:
    desc: "Build the docker image. We need a TeX live 2021 or eariler distribution to correctly represent the ceur style."
    cmds:
      - docker build -t {{.LATEX_IMAGE}} .

  build:
    desc: Batch build all submissions
    cmds:
      - |
        for submission_id in {{.submission_ids}}
        do
          submission_id=$submission_id task submission:build || true
        done
      - task: submission:build
        vars:
          submission_id: Preface

  clean:
    desc: Batch clean all submission directories
    cmds:
      - |
        for submission_id in {{.submission_ids}}
        do
          submission_id=$submission_id task submission:clean
        done
      - task: submission:clean
        vars:
          submission_id: Preface

  cherry-diff:
    desc: Compare the built submission pdf to the currently commited pdf in the HEAD. This requires https://github.com/white-gecko/git-cherry-file
    cmds:
      - |
        for submission_id in {{.submission_ids}}
        do
          git-cherry-file HEAD ${submission_id}/main.pdf ${submission_id}/cherry.pdf
          diffpdf ${submission_id}/main.pdf ${submission_id}/cherry.pdf
          rm ${submission_id}/cherry.pdf
        done

  open:
    desc: Open all submission pdfs for visual verification
    cmds:
      - |
        for submission_id in {{.submission_ids}}
        do
          xdg-open $submission_id/main.pdf
        done
      - task: submission:open
        vars:
          submission_id: Preface

  diff:
    desc: Perform a batch comparison on all build submission pdfs
    cmds:
      - |
        for submission_id in {{.submission_ids}}
        do
          submission_id=$submission_id task submission:diff
        done

  submission:diff:
    desc: Compare a built submission PDF to the original pdf submitted to easychair
    cmds:
      - diffpdf {{.submission_id}}/main.pdf {{.origianl_submissions}}/D2R223_paper_{{.submission_id}}.pdf

  submission:build:
    desc: Build an individual submission from sources
    cmds:
      - |
        cd {{.submission_id}}
        exec docker run --rm -i --net=none -v "$PWD":/data "{{.LATEX_IMAGE}}" latexmk -lualatex -shell-escape main.tex
    status:
      - test ! -f {{.submission_id}}/main.tex

  submission:clean:
    desc: Clean a submission directory
    cmds:
      - |
        cd {{.submission_id}}
        exec docker run --rm -i --net=none -v "$PWD":/data "{{.LATEX_IMAGE}}" latexmk -c -lualatex main.tex
        rm main.abs || true
        rm main.xmpdata || true
        rm pdfa.xmpi || true
        rm creationdate.lua || true
        rm creationdate.timestamp || true
        rm *.xdv || true
        rm *.bbl || true
        rm -r _minted-main/ || true
    status:
      - test ! -f {{.submission_id}}/main.tex
