name: Comment on pull request
on:
  workflow_run:
    workflows: ['Build Paper Sources and Submission Files']
    types: [completed]
jobs:
  pr_comment:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - id: 'pr-number'
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const {owner, repo} = context.repo;
            const pullHeadSHA = '${{github.event.workflow_run.head_sha}}';
            const pullUserId = ${{github.event.sender.id}};
            const prNumber = await (async () => {
              const pulls = await github.rest.pulls.list({owner, repo});
              for await (const {data} of github.paginate.iterator(pulls)) {
                for (const pull of data) {
                  if (pull.head.sha === pullHeadSHA && pull.user.id === pullUserId) {
                    return pull.number;
                  }
                }
              }
            })();
            if (!prNumber) {
              return core.error(`No matching pull request found`);
            }
            return prNumber;
      - id: 'artifacts-text'
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            return allArtifacts.data.artifacts.reduce((acc, item) => {
              if (item.name === "assets") return acc;
              acc += `
              - [${item.name}.zip](https://nightly.link/${context.repo.owner}/${context.repo.repo}/actions/artifacts/${item.id}.zip)`;
              return acc;
            }, '### Build Artifacts');
      - name: Comment on issue by current pull request
        uses: alexrogalskiy/github-action-issue-commenter@master
        with:
          message: "Here are the artifacts for this pull-request:\n\n${{ steps.artifacts-text.outputs.result }}\n\nNow download the `Forms to Sign.zip`, print, sign, scan, and upload the form. IMPORTANT it must be hand signed."
          requestId: ${{ steps.pr-number.outputs.result }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
